---
# Tilibot Configuration File

#
Baud-Rate: 1000000 # Dynamixel default baudrate is 57,600                                           #0
Position-Angle-File: /home/pi/TilibotToolbox/ref_data/Kinematics_5.csv                              #1
Positions-Per-Stride: 22 # Amount of positions limbs will hit before completing a single stride     #2
Stride-Time: 10.0 # in seconds, Float                                                               #3
Stride-Amount: 2 # Entire strides to execute before finishing movement                              #4
##

#
Servos-Connected:                                                                                   #5
  - Yes # Servo #1
  - Yes # Servo #2
  - Yes # Servo #3
  - Yes # Servo #4
  - Yes # Servo #5
  - Yes # Servo #6
  - Yes # Servo #7
  - Yes # Servo #8
  - Yes # Servo #9
  - Yes # Servo #10
  - Yes # Servo #11
  - Yes # Servo #12
  - Yes # Servo #13
  - Yes # Servo #14
  - Yes # Servo #15
  - Yes # Servo #16
  - No # Servo #17
  - Yes # Servo #18
  - Yes # Servo #19
  - Yes # Servo #20
  - Yes # Servo #21
  - Yes # Servo #22
  - Yes # Servo #23
  - Yes # Servo #24
Limbs-Connected:                                                                                    #6
  - Yes # Front Right Limb
  - Yes # Front Left Limb
  - Yes # Back Right Limb
  - Yes # Back Left Limb
  - Yes # Neck Limb
  - Yes # Spine Limb
  - Yes # Tail Limb
Body-Sensors-Connected: No                                                                            #7
##

# Stance / Swing Ratios
Forelimb-Stance: 5.211718                                                                            #8
Forelimb-Swing: 3.028282                                                                             #9
Hindlimb-Stance: 4.892994                                                                           #10
Hindlimb-Swing: 3.347006                                                                            #11
Ratio-Time: 8.24                                                                                    #12
##

# Pick Only One of the Following Options
Move-Single-Servo: No                                                                               #13
Single-Servo-To-Move: 0 # Put 0 if Move Single Servo is "no"                                        #14
Move-Multiple-Servos: Yes                                                                            #15
Servos-To-Move: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16] # Leave list empty [] if Move Multiple Servos is "no" #16
##

#
Home-Speed: 50                                                                                      #17
Output-File-Name: TestOutFile                                                                       #18
Output-File-Directory: /home/pi/TilibotToolbox/out_data/                                            #19
##

# Output Information (Check all that apply) 
Position: No                                                                                       #20
Speed: No                                                                                          #21
Time: No                                                                                            #22
Position-Index: No                                                                                  #23
Stride-Count: No                                                                                    #24
Current: No                                                                                         #25
Voltage: No                                                                                         #26
Temperature: No                                                                                     #27
##

# Pre-Run Behaviors
Neck-Straight: True                                                                                 #28
Spine-Straight: True                                                                                #29
Tail-Straight: True                                                                                 #30
##

#
Silence-Extraneous-Output: No                                                                       #31  
Run-Digital-Only: No          # Not Fully set up yet, in Test phase                                 #32  
##
